<?php

// Exit if accessed directly
if ( !defined('ABSPATH')) exit;

/**
 *
 * WARNING: Please do not edit this file in any way
 *
 * load the theme function files
 */

/**
 * Wrapper to require
 * Just require theme function files
 *
 * @param string $file The function file to be required
 */
function require_fragment($file) {
  require(get_stylesheet_directory() . $file);
}

require_fragment('/includes/theme_configuration.php' );
require_fragment('/includes/hooks.php' );
require_fragment('/includes/functions.php' );
require_fragment('/includes/utility_functions.php' );

// Plugin files go here
require_fragment('/includes/plugins/galleria/galleria.php' );

// Pages templates - data init functions
require_fragment('/includes/pages/newsletter/pages-newsletter.php' );
require_fragment('/includes/pages/people-list/pages-people-list.php' );

// Pods function files go below

// Pods UI
require_fragment('/includes/pods/ui/lsecities-pods-ui.php' );

// Pods document types
require_fragment('/includes/pods/pods/article/pods-article.php' );
require_fragment('/includes/pods/pods/conference/pods-conference.php' );
require_fragment('/includes/pods/pods/conference/pods-conference-live.php' );
require_fragment('/includes/pods/pods/event/pods-event.php' );
require_fragment('/includes/pods/pods/event-programme/pods-event-programme.php' );
require_fragment('/includes/pods/pods/list/pods-list.php' );
require_fragment('/includes/pods/pods/slider/pods-slider.php' );
require_fragment('/includes/pods/pods/research-project/pods-research-project.php' );
